{
    "exception": {
        "internalServerError": "An unexpected error has occurred."
    }
}